// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjFINTo1nalIo13chKSz06micHCeQIwm0',
    appId: '1:959824324077:android:7b7bfc3545a7d901f933e4',
    messagingSenderId: '959824324077',
    projectId: 'abdultesting-65747',
    storageBucket: 'abdultesting-65747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8joum_JU2D56urOwi_L-Wn3VZx2E-eh0',
    appId: '1:959824324077:ios:309e464a976da24cf933e4',
    messagingSenderId: '959824324077',
    projectId: 'abdultesting-65747',
    storageBucket: 'abdultesting-65747.firebasestorage.app',
    androidClientId: '959824324077-vh9sepmv3hpb4kfdmdk1mg1dp1ctnh7p.apps.googleusercontent.com',
    iosClientId: '959824324077-oq2r9ho1n84fo15boice3s9bu3eoh0qt.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerce',
  );

}